[link text](https://)SPAM EMAIL DETECTOR NAIVE BAYES ( DATA INFO:::: SPAM = 1 ;HAM =0 )

RELATED PROJECT :: FACEBOOK, YOUTUBE FAKE COMMENT

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df=pd.read_csv('/content/emails.csv')
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [9]:
df['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [10]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [11]:
df.duplicated().sum()

33

In [12]:
df.drop_duplicates(inplace=True)
#df.dropna(inplace=True)
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [13]:
df['spam'].value_counts()

spam
0    4327
1    1368
Name: count, dtype: int64

TEXT DATA ER JONNO MULTINOMIAL NAIVE BAYES BEST

In [14]:
from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import StandardScaler === It is for only numeric data
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [15]:
x=df.text.values
y=df.spam.values

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [31]:
cv=CountVectorizer()
cv.fit(x_train)
x_train_abc=cv.transform(x_train)





In [32]:
x_train_abc.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
model=MultinomialNB()
model.fit(x_train_abc,y_train)

MultinomialNB()

TRAIN AND MODEL FITTING FINISH .... NOW ITS THE TIME TO TEST

In [34]:
x_test_abc=cv.transform(x_test)


In [33]:
x_test_abc.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]])

MEASURE ACCRUACY

In [37]:
model.score(x_test_abc,y_test)


0.9938542581211589

In [38]:
model.score(x_train_abc,y_train)

0.995171202809482

EXAMPLE


In [40]:
mails=[
       'Hey mohan, can we get together to watch footbal game tomorrow?',
       'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [41]:
cv_mails=cv.transform(mails)


In [42]:
model.predict(cv_mails)

array([0, 1])

In [ ]:
0= real mail
1= spam